= Bare Git Repo
:keywords: git, software
:revdate: July 2023

== What is a bare git repo?

Whenever you clone a repo, a directory is created with 2 components:

. `.git` directory
    .. All the metadata the git repo needs: branches, logs, objects, commits, etc
. Working directory
    .. All the files that are in the default branch of the repo
    .. You can modify these files, commit, and push them
    .. This is what you regularly deal with

.Normal Repo example
----
normal-repo
├── .git                         <-- .git directory
│   ├── branches
│   ├── config
│   ├── description
│   ├── HEAD
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   └── ...
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   └── refs
│       ├── heads
│       └── tags
└── README.adoc                  <-- working tree
----

So what is a bare git repo? It's just a repo with only the contents of the `.git` directory.

.Bare Repo Example
----
bare-repo
├── branches
├── config
├── description
├── HEAD
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   └── ...
├── info
│   └── exclude
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
----

Notice how there is no `.git` folder, the contents of the `.git` folder are at the top level.

NOTE: There is one other difference, bare repos have `bare = true` in the `config` file

== Why use a bare git repo?

=== Servers

Bare repos are used for git servers, meaning a repo that developers push to and pull from.
Let's say you want to host a local git server instead of using GitHub (GitHub uses bare repos as well), you could create the repo then multiple developers could clone it and push their changes to it.

=== Git Worktrees

While they are generally used on the server side, developers can make bare clones of repos which work well with the git work tree flow.
See xref:git-worktrees.adoc[] for more information.

== How do I make a bare git repo?

