= Bare Git Repos
:keywords: git, software
:revdate: July 2023

== What is a bare git repo?

Let's first define what a normal (non-bare) repo is. When you clone a repo normally, a directory is created with 2 components:

. `.git` directory
    .. All the metadata the git repo needs: branches, logs, objects, commits, etc
. Working directory (all the other files)
    .. All the files that are in the default branch of the repo
    .. You can modify these files, commit, and push them
    .. This is what you regularly deal with

You can see the components in this example git repo:

.Normal Repo example
----
normal-repo
├── .git                         <-- .git directory
│   ├── branches
│   ├── config
│   ├── description
│   ├── HEAD
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   └── ...
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   └── refs
│       ├── heads
│       └── tags
└── README.adoc                  <-- working directory
----

A bare repo is just a repo with only the contents of the `.git` directory.
There is no `.git` folder, the contents of the `.git` folder are at the top level.

.Bare Repo Example
----
bare-repo
├── branches
├── config
├── description
├── HEAD
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   └── ...
├── info
│   └── exclude
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
----


NOTE: There is one other difference between bare repos and normal repos: bare repos have `bare = true` in the `config` file.

== Why use a bare git repo?

=== Servers

Bare repos are used for git servers (i.e., a repo that developers can push to and pull from).
Let's say you want to host a local git server instead of using GitHub, you could create a bare repo then multiple developers could clone it and push their changes to it.
This allows you to host your repo anywhere without depending on a service like Github.

=== Git Worktrees

While they are generally used on the server side, developers can make bare clones of repos which work well with git worktrees.
Git worktrees are a very useful concept, see xref:git-worktrees.adoc[] for more information.

== How do I make a bare git repo?

Just use the `--bare` flag when initializing the repo. For example:

[,bash]
----
mkdir bare-repo-example && cd bare-repo-example
git init --bare
----

== How do I convert my repo into a bare repo?

. Extract the contents of the `.git` folder to your new repo folder
. Set the `bare` boolean to true (can also be done by modifying the config file directly)
    .. `git config --bool core.bare true`
