site:
  title: Colby's Corner
  start_page: tech-notes::index.adoc
content:
  sources:
  - url: ./
    branches: antora2-merge
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    sectanchors: true
  extensions:
  - asciidoctor-plantuml
runtime:
  fetch: true
    # Not sure if I want this yet because it turns sections blue
    # sectlinks: true
