= Volatile and Synchronized and Atomic, Oh My!
:keywords: java, atomic, cas, volatile, memory-visibility, synchronized

Java provides several constructs for mitigating the complexities of concurrency.
Their differences seem subtle but can have drastic effects on applications.
This article explains why these exist and when to use each one.

== The Difficulties of Concurrency

To understand the differences, we first need to understand the 2 main difficulties with concurrent programming: memory visibility and atomicity.

=== Memory Visibility

Consider this program:

[source,java]
----
import java.util.concurrent.TimeUnit;

class Example {

    private static boolean stopRequested = false;

    public static void main(String[] args) throws InterruptedException {
        Thread backgroundThread = new Thread(() -> {
            int i = 0;
            while (!stopRequested)
                i++;
        });

        backgroundThread.start();
        TimeUnit.SECONDS.sleep(1);
        stopRequested = true;
    }
}
----

Try running it, and it probably will not terminate; the background thread will always think `stopRequested` is still false and continue to loop.
Why? The java memory model does not guarantee that writes on a variable in one thread will appear in another thread.
In other words, memory modifications are not always visible to other threads.

=== Atomicity

Consider this program:

[source,java]
----
int x = 1;
x++;
----

While `x++` is one line of code, it is actually several instructions:

. Load value for x
. Increment the value by 1
. Store the new value

Consider 2 threads `a` and `b` running this line simultaneously:

. a loads the current value of x: 1
. b loads the current value of x: 1
. a increments the value 2
. a increments the value 2
. a stores 2 into x
. b stores 2 into x

So we have 2 increment operations but the final value is only incremented by 1, clearly that is wrong.
Meaning operations (even 1 liners) can be interleaved in strange ways that result in bugs - they are not *atomic*.


== Solutions for Concurrency

These constructs are different approaches to mitigating these difficulties:

=== Volatile

Volatile addresses the memory visibility problem: it tells java to not place the variable in a register and to instead grab the value from the main cache.
This means volatile would work for our loop example but not for our `x++` example.

=== Synchronized
Synchronized blocks have stronger semantics than volatile; they address the memory visibility problem but *also address the atomicity problem* by ensuring only 1 thread is running the sync block at a time.
This means synchronized blocks would work for both examples, but they are less performant than volatile variables due to locking.

=== Atomic Variables
Atomic variables have volatile semantics with `get` and `set` but also solve the atomicity problem via compare and set (CAS) operations (`compareAndSet` method).
Unlike synchronized blocks, they are nonblocking, resulting in better performance than synchronized blocks in _most_ cases.

=== What is CAS?
CAS is a form of non-locking synchronization.
It is an atomic instruction that checks the current value and only applies the new value if the current value equals the expected value.
They can be more performant than traditional locks because they don't actually lock or have to reschedule threads.
The main disadvantage of CAS is it's harder to design algorithms around.
They are actually less performant when contention is very high (but still generally faster in most real world cases)

== Summary

|===
| | Volatile | Synchronized | Atomic

| Are changes visible to other threads?
| Y
| Y
| Y

| Does it enable atomicity?
| N
| Y
| Y
|===
