= Makefiles are still useful
:keywords: make, makefile, build

Yes, that 50 year-old program your professor tried to get you to use is still useful.
Modern build tools like `maven`, `gradle`, and `bazel` have taken over, but `make` still deserves to be in your toolkit for small tasks.

== A use case for make

Let's walk through a use case for make: you just learned asciidoc is better than markdown and want to try it out.
You download https://asciidoctor.org[asciidoctor] and make your first asciidoc:

.example.adoc
[source,adoc]
----
= Makefiles are still useful

Introduction text

== Makefile Example

Example text
----

You read the https://docs.asciidoctor.org/asciidoctor/latest/cli/[documentation] and convert your first asciidoc into html:

[source,bash]
----
asciidoctor example.adoc
----

You open your generated html file:

[source,bash]
----
open example.html
----

You get excited and make more asciidocs. How do you need convert them all? Easy, a wildcard:

[source,bash]
----
asciidoctor *.adoc
----

You decide you want your generated files to be separate from your source files, so you tell asciidoctor to place them in a `build` directory:

[source,bash]
----
asciidoctor -D build *.adoc
----

You now have a basic development cycle:

. make your change
. build with your asciidoctor command
. open your generated files to review them

You do not want to type `asciidoctor -D build *.adoc` every time you make a change though, so you use your bash history to repeat the command.
This works, but what if you want to allow others to use your project?
What if you lose your bash history?
You do the _almost_ right thing... you make a build script:

.build.sh
[source,bash]
----
asciidoctor -D build *.adoc
----

Then you make a `run.sh` script for previewing and a `clean.sh` script for cleaning the generated files.
Your `run.sh` technically depends on the build command though - how do you ensure the project has been built before running?
Make a `build_and_run` script? No! There's a better way!

== The Makefile

Okay, I think you see where I'm going - a `Makefile` is a clean and simple way to do all of this:


.Makefile
[source,Makefile]
----
build:
    asciidoctor -D build *.adoc
run: build
    open build/example.html
clean:
    rm -rf build

.PHONY: clean run
----

TIP: I won't go into much detail with `Makefile` syntax here because there are already many resources on it.
I highly recommend https://makefiletutorial.com[makefiletutorial] if you want to learn more.

To use it, just run `make`:

[horizontal]
make build:: converts all `adoc` files in the content folder into `html` and stores them in a `build` folder
make run:: runs `make build` if the build directory does not exist then opens `index.html` for previewing
make clean:: deletes all the generated `html`
make clean run:: runs the `clean` target then the `run` target
make:: runs the default target which is the first specified target (`build` in this example)


Now your development cycle is simply:

. make your change
. execute `make clean run`

You don't have to remember a script name and the purpose of the file is obvious for others that are using your code.

== So why should you use make?

[horizontal]
Expressive::
A lot can be accomplished with little code.
The example above defined a build process in a few lines.
Ubiquitous::
There is no need to worry about installing make. It's already in all your servers.
Shells can autocomplete the targets that are defined in your `Makefile`.
Even vim has a built in `:make` command.
Versatile::
Make does not lock you into any specific language or technology. If you can do it in the terminal, you can do it in make.
Consistent::
Instead of having a different `bash` script in each project you can have a `Makefile` and simply run `make`.
There is no need to remember the name of the various commands and script files.

== How should you use make?

.Do's and Dont's of make
|===
|Do...|Don't...

a|

* use make for small projects, prototyping, and non-standard setups
* keep your commands short and simple
* extract large code blocks into a script and call it from your `Makefile`

a|

* use make for large projects or standard projects like java (`maven` or `gradle` would serve you better)
* write large scripts inside of your `Makefile`
|===
