@startuml
hide empty description
[*] --> SelectState: select

SelectState --> FromState: from
FromState --> WhereState: where
FromState --> OrderByState: orderBy
WhereState --> OrderByState: orderBy
WhereState --> AndState: and
AndState --> AndState: and
AndState --> OrderByState: orderBy

AndState --> [*]
FromState --> [*]
WhereState --> [*]
OrderByState --> [*]
@enduml
